# TODO use `pnpm` linker, currently fails with Storybook Playwright integration: https://github.com/storybookjs/storybook/issues/23654
# nodeLinker: pnpm
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.1.cjs
